### PR TITLE
Handler function signature is function(event, direction)

### PR DESCRIPTION
**Pull request by fcsobel**
Maybe I am missing something but I had to adjust to get this to work with latest jquery waypoint. The handler function signature is function(event, direction) where event is a standard jQuery Event Object and direction is a string, either 'down' or 'up' indicating which direction the user is scrolling.

### CODE REVIEW

**Comment by cjsaylor** [comment]
@fcsobel What version of jQuery waypoints does this not work with? The project's bower file specifies `~2.0.5`, so unless they broke BC in a patch version not sure how that is possible.

**Comment by fcsobel** [comment]
Using 3.1.1 waypoints so makes sense

**Comment by young-steveo** [comment]
@fcsobel Thanks for the PR.  I wasn't aware of waypoints v3.  It looks like it doesn't use jQuery as a dependency.  We could try to support it, but I think we would need to release angular-waypoints v2.0 since this is a BC break (notice your PR breaks our travis tests).  Also, we'd need to review what other BC changes they have made from jQuery waypoints 2.0.5

**Comment by young-steveo** [comment]
@fcsobel FYI, I was researching the new Waypoints 3 API in order to upgrade our library to use the latest verion; it seems that the function signature for the handler has not changed.  As you can see [here](https://github.com/imakewebthings/waypoints/blob/master/src/group.js#L52), they still only pass the direction to the callback, not an event.

(Incidentally, none of the documentation in their API docs mention an event either)

**Pull request closed without merging**
